services:
  web:
    # このフォルダ（.）にあるDockerfileを使って構築する
    build: .

    # パソコンの5000番ポートと、コンテナの5000番ポートを繋ぐ（画面を見るための扉）
    ports:
      - "5000:5000"

    # パソコンの「src」フォルダを、コンテナの「/app/src」に同期する（コードの変更を即反映させるため）
    volumes:
      - ../src:/app/src